[project]
name = "meross-controller"
version = "0.1.0"
requires-python = "~=3.11.0"
dependencies = [
    "apscheduler~=3.6.3",
    "meross-iot>=0.4.9.0",
    "mysql-connector-python==8.0.29",
    "python-telegram-bot~=13.14",
    "tzlocal<3.0",
]
